name: travelgenie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  flutter_signin_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#0D6EFD"
  image: assets/splash_logo.png
  android_12:
    color: "#0D6EFD"
    image: assets/splash_logo.png
  android: true
  ios: true

  
  android_gravity: center
  ios_content_mode: scaleAspectFit


flutter:
  uses-material-design: true

assets:
  - assets/images/
  - google_fonts/
  - assets/images/google_g.svg
